apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: platform-team
spec:
  # Tenant owners (Azure AD group)
  owners:
    - name: platform-engineers
      kind: Group

  # Limit to 5 namespaces per tenant
  namespaceOptions:
    quota: 5

  # Node selector - force pods to run on Capsule node pool
  nodeSelector:
    tenant-mode: soft-isolation

  # Default resource limits for every container
  limitRanges:
    items:
      - limits:
          - type: Container
            default:
              cpu: "1"
              memory: "1Gi"
            defaultRequest:
              cpu: "100m"
              memory: "128Mi"
            max:
              cpu: "4"
              memory: "8Gi"
            min:
              cpu: "10m"
              memory: "64Mi"

  # Aggregate quota across all namespaces in this tenant
  resourceQuotas:
    items:
      - hard:
          limits.cpu: "40"
          limits.memory: "80Gi"
          requests.cpu: "20"
          requests.memory: "40Gi"
          requests.storage: "500Gi"
          persistentvolumeclaims: "20"
          pods: "200"
          services: "50"
          services.loadbalancers: "5"

  # Network isolation - only allow traffic within tenant
  networkPolicies:
    items:
      - policyTypes:
          - Ingress
          - Egress
        podSelector: {}
        ingress:
          - from:
              - namespaceSelector:
                  matchLabels:
                    capsule.clastix.io/tenant: platform-team
        egress:
          # Allow traffic within tenant
          - to:
              - namespaceSelector:
                  matchLabels:
                    capsule.clastix.io/tenant: platform-team
          # Allow DNS
          - to:
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: kube-system
            ports:
              - protocol: UDP
                port: 53
          # Allow external HTTPS
          - to:
              - podSelector: {}
            ports:
              - protocol: TCP
                port: 443
              - protocol: TCP
                port: 80

  # Restrict ingress hostnames to tenant-specific pattern
  ingressOptions:
    allowedHostnames:
      allowedRegex: ".*\\.platform-team\\.srekubecraft\\.io$"

  # Only allow specific storage classes
  storageClasses:
    allowed:
      - managed-premium
      - managed-csi

  # Restrict container registries
  containerRegistries:
    allowed:
      - "acr*.azurecr.io"
      - "docker.io/library"
      - "ghcr.io"
      - "quay.io"

  # Service account annotations for workload identity
  serviceOptions:
    additionalMetadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        tenant: platform-team
        cost-center: "engineering"
        managed-by: "capsule"

  # Priority classes allowed
  priorityClasses:
    allowed:
      - tenant-low
      - tenant-medium
    matchLabels:
      tenant: platform-team

  # Pod Security Standards enforcement
  podOptions:
    additionalMetadata:
      labels:
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/warn: restricted
