apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.20.2
    chart: external-secrets
    helm:
      values: |
        installCRDs: true

        # Deploy to system node pool with tolerations
        nodeSelector:
          nodepool-type: system

        tolerations:
          - key: CriticalAddonsOnly
            operator: Exists

        webhook:
          nodeSelector:
            nodepool-type: system
          tolerations:
            - key: CriticalAddonsOnly
              operator: Exists

        certController:
          nodeSelector:
            nodepool-type: system
          tolerations:
            - key: CriticalAddonsOnly
              operator: Exists

        # Service account for workload identity
        serviceAccount:
          create: true
          name: external-secrets-operator
          annotations:
            azure.workload.identity/client-id: "${MANAGED_IDENTITY_CLIENT_ID}"
            azure.workload.identity/tenant-id: "${TENANT_ID}"

        # Resource limits
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
